kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubit
subjects:
- kind: ServiceAccount
  name: kubit
roleRef:
  kind: Role
  name: kubit
  apiGroup: rbac.authorization.k8s.io
